workflows:
  ios:
    name: iOS Workflow
    environment:
      vars:
        FLUTTER_VERSION: stable
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Set iOS deployment target and excluded archs for simulator
        script: |
          cd ios
          # Ensure the Podfile starts with the required platform
          echo "platform :ios, '12.0'" > Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  use_frameworks!" >> Podfile
          echo "  use_modular_headers!" >> Podfile
          echo "  flutter_application_path = '../../'" >> Podfile
          echo "  load File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb')" >> Podfile # Fixed the path
          echo "end" >> Podfile
          
          # Add the post_install block to the Podfile
          echo "post_install do |installer|" >> Podfile
          echo "  installer.pods_project.targets.each do |target|" >> Podfile
          echo "    if target.name == 'BoringSSL-GRPC'" >> Podfile
          echo "      target.source_build_phase.files.each do |file|" >> Podfile
          echo "        if file.settings && file.settings['COMPILER_FLAGS']" >> Podfile
          echo "          flags = file.settings['COMPILER_FLAGS'].split" >> Podfile
          echo "          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }" >> Podfile
          echo "          file.settings['COMPILER_FLAGS'] = flags.join(' ')" >> Podfile
          echo "        end" >> Podfile
          echo "      end" >> Podfile
          echo "    end" >> Podfile
          echo "  end" >> Podfile
          echo "end" >> Podfile

          # Install the pods
          pod install
      - flutter clean
      - flutter pub get
      - flutter build ios --no-codesign
    artifacts:
      - build/ios/ipa
